// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evrnsemreovglfggjmrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2cm5zZW1yZW92Z2xmZ2dqbXJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNzY1NzksImV4cCI6MjA2MTg1MjU3OX0.T9Yomsnflp9YwI6BOZVPboNeWnjzG0bjJuKKlrOYEYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);